### PR TITLE
Implement React Redux configurations

### PR DESCRIPTION
**Pull request by rusiruavb**
Add React Redux boiler plate code

### CODE REVIEW

**Comment by rusiruavb** [comment]
The build did not pass. But not a problem though. Review and merge to the development.

**Review by rusiruavb — COMMENTED** [review]
LGTM

**Review by RaveenaWickramasinghe — APPROVED** [review]
LGTM

**Comment by RaveenaWickramasinghe** [comment]
> The build did not pass. But not a problem though. Review and merge to the development.

The Merging in impossible due the failing in the build

**Pull request merged**
